const CartActionTypes = {
  TOGGOLE_CART_HIDDEN: 'TOGGOLE_CART-HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
};
export default CartActionTypes;
